module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats Trail',
    'Village Trail',
    'Canyon Trail',
    'Pond Trail',
    'Group Trail',
    'Horse Trail',
    'Ghost Town Trail',
    'Trail',
    'Dispersed Trail',
    'Backcountry Trail',
    'River Trail',
    'Creek Trail',
    'Creekside Trail',
    'Bay Trail',
    'Spring Trail',
    'Bayshore Trail',
    'Sands Trail',
    'Mule Trail',
    'Hunting Trail',
    'Cliffs Trail',
    'Hollow Trail'
]